version: "3.9"

services:
  introducemeia_app:
    build: .
    container_name: introducemeia_app
    volumes:
      - ./:/var/www/html
    networks:
      - introducemeia_app
    depends_on:
      - introducemeia_webserver
      - introducemeia_database
      - introducemeia_redis
    
  introducemeia_webserver:
    image: nginx:latest
    container_name: introducemeia_webserver
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - introducemeia_app

  introducemeia_database:
    image: mysql:5.7
    container_name: introducemeia_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_introducemeia_data:/var/lib/mysql
    networks:
      - introducemeia_app

  introducemeia_redis:
    container_name: introducemeia_redis
    image: 'redis:latest'
    restart: always
    ports:
      - "6379:6379"
    networks:
      - introducemeia_app
    
networks:
  introducemeia_app:
    driver: bridge

volumes:
  db_introducemeia_data: